camunda.bpm:
  admin-user:
    id: admin
    password: admin
    firstName: Administrator
  filter:
    create: 'All tasks'
  deployment-resource-pattern: 'classpath:processes/*.bpmn'
#  process-engine-name: "EngineName"

camunda:
  bpm:
    eventing:
      history: true
    auto-deployment-enabled: true
---
spring:
  datasource:
    jdbcUrl: 'jdbc:h2:mem:camunda;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE'
    username: sa
    password: null
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
---
#custom Camunda rest api
spring:
  jersey:
    application-path: camunda-api
